// pdfGenerator.ts
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const theme = {
  primary: "#4f46e5", // Indigo-600
  secondary: "#818cf8", // Indigo-400
  text: "#1f2937", // Gray-800
  lightText: "#6b7280", // Gray-500
  white: "#ffffff",
  tableHeader: "#4338ca", // Indigo-700
};

export interface PDFColumn {
  title: string;
  dataKey: string;
  align?: "left" | "center" | "right";
}

export interface PDFData {
  [key: string]: string | number;
}

export interface PDFOptions {
  title: string;
  subtitle?: string;
  columns: PDFColumn[];
  data: PDFData[];
  fileName?: string;
}

export const generatePDF = ({
  title,
  subtitle,
  columns,
  data,
  fileName,
}: PDFOptions) => {
  const doc = new jsPDF();

  // --- HEADER ---
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(theme.primary);
  doc.text("EduMate", 14, 20);

  if (subtitle) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(theme.lightText);
    doc.text(subtitle, 14, 26);
  }

  doc.setFontSize(10);
  doc.setTextColor(theme.text);
  const date = new Date().toLocaleDateString();
  doc.text(`Report Date: ${date}`, 196, 20, { align: "right" });
  doc.text(title, 196, 26, { align: "right" });

  doc.setDrawColor(theme.lightText);
  doc.setLineWidth(0.5);
  doc.line(14, 32, 196, 32);

  // --- TABLE ---
  const tableColumns = columns.map((col) => col.title);
  const tableRows = data.map((row) => columns.map((col) => row[col.dataKey]));

  autoTable(doc, {
    head: [tableColumns],
    body: tableRows,
    startY: 40,
    styles: { fontSize: 10, textColor: theme.text },
    headStyles: {
      fillColor: theme.tableHeader,
      textColor: theme.white,
      fontStyle: "bold",
    },
    alternateRowStyles: { fillColor: "#f3f4f6" },
    columnStyles: columns.reduce((acc, col, index) => {
      if (col.align) acc[index] = { halign: col.align };
      return acc;
    }, {} as any),
  });

  // --- FOOTER ---
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(theme.lightText);
    doc.text(
      `Generated by EduMate System - Page ${i} of ${totalPages}`,
      14,
      doc.internal.pageSize.height - 10
    );
  }

  doc.save(fileName || "EduMate_Report.pdf");
};
